---
title: Garden Cottage, a luxury rental cottage in Crail
timezone: UTC
collections:
  - accommodation
  - bookings
  - contact
  - reviews
  - your-stay
  - uploads
name: Garden Cottage, Crail
plugins:
- jekyll-admin
jekyll_admin:
  hidden_links:
  - posts
  - configuration
