---
title: Garden Cottage, a luxury rental cottage in Crail
timezone: UTC
permalink: pretty
collections:
  accommodation:
    title: Accommodation
    output: true
  bookings:
    title: Bookings
    output: true
  contact:
    title: Contact
    output: true
  posts:
    title: Posts
    output: true
  reviews:
    title: Reviews
    output: true
  uploads:
    title: Uploads
    output: false
  your-stay:
    title: Your Stay
    output: true
name: Garden Cottage, Crail
plugins:
- jekyll-admin
jekyll_admin:
  hidden_links:
  - posts
  - configuration
