---
title: Garden Cottage, Crail
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Garden Cottage, Crail
plugins:
  - jekyll-admin
jekyll_admin:
  hidden_links:
    - posts
    - configuration
    - uploads
