backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

editor:
  preview: false

publish_mode: editorial_workflow
media_folder: "assets/images"
display_url: https://www.gardencottagecrail.co.uk

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "homepage"}
          - {label: "Order", name: "order", widget: "hidden", default: 1}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Images
            name: images
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Image, name: image, widget: image}
      - label: "Accommodation"
        name: "accommodation"
        file: "_data/accommodation.yml"
        fields:
          - label: "Areas"
            name: "areas"
            widget: list
            fields:
              - {label: Title, name: title, widget: string, default: "Accommodation"}
              - {label: "Class", name: "class", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
              - label: Images
                name: images
                widget: object
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Image, name: image, widget: image}
      - label: "Reviews"
        name: "reviews"
        file: "_data/reviews.yml"
        fields:
          - label: Reviews
            name: reviews
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Reviews"}
              - {label: "Rating", name: "rating", widget: "number"}
              - {label: "Date", name: "date", widget: "string"}
              - {label: "Comment", name: "comment", widget: "string"}
              - {label: "Reviewer Name", name: "name", widget: "string"}
      - label: "Bookings"
        name: "bookings"
        file: "bookings.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Bookings and Availability"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "full-length"}
          - {label: "Order", name: "order", widget: "hidden", default: 3}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Contact"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "contact"}
          - {label: "Order", name: "order", widget: "hidden", default: 6}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Your Stay"
        name: "your-stay"
        file: "your-stay.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Your Stay"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "full-length"}
          - {label: "Order", name: "order", widget: "hidden", default: 4}
          - {label: "Body", name: "body", widget: "markdown"}