backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "Content", name: "content", widget: "markdown"}
          - label: Image
            name: image
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Image, name: image, widget: image}
      - label: "Accommodation"
        name: "accommodation"
        file: "accommodation.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Image
            name: image
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Image, name: image, widget: image}