backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "data"
    label: "Data"
    folder: "_data"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language"}