backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "homepage-gallery"
    label: "Homepage Gallery"
    folder: "_data/"
    create: true
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language"}